# Generated by Django 4.2.7 on 2024-03-26 14:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Buddy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("model", models.CharField(max_length=255)),
                ("system_message", models.TextField()),
            ],
            options={
                "verbose_name_plural": "buddies",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["public_id"], name="buddies_bud_public__085d7e_idx"
                    )
                ],
            },
        ),
    ]
