# Generated by Django 4.2.7 on 2024-03-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0002_remove_node_is_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="subnodes",
            field=models.ManyToManyField(related_name="supernodes", to="nodes.node"),
        ),
    ]
