# Generated by Django 4.2.7 on 2024-03-12 17:24
import uuid

from django.conf import settings
from django.db import migrations, models


def get_document_type(apps, schema_editor) -> None:
    Document = apps.get_model("nodes", "Document")

    for document in Document.objects.all():
        if document.json.get(settings.NODE_CRDT_KEY, {}).get("type") == "doc":
            document.document_type = "EDITOR"
        elif "nodes" in document.json and "edges" in document.json:
            document.document_type = "GRAPH"
        elif "nodes" in document.json and "deletedNodes" in document.json:
            document.document_type = "SPACE"
        else:
            document.document_type = "UNKNOWN"
        document.save()


class Migration(migrations.Migration):
    dependencies = [
        ("nodes", "0007_auto_20240312_1713"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[("EDITOR", "Editor"), ("SPACE", "Space"), ("GRAPH", "Graph")],
                default="asdf",
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="document",
            name="public_id",
            field=models.UUIDField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="node",
            name="public_id",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="space",
            name="public_id",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.UniqueConstraint(
                fields=("public_id", "document_type"), name="unique_public_id_and_type"
            ),
        ),
        migrations.RunPython(get_document_type, reverse_code=migrations.RunPython.noop),
    ]
