# Generated by Django 4.2.7 on 2024-03-13 14:43

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0010_auto_20240312_1839"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="document",
            name="document_change",
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="document",
            trigger=pgtrigger.compiler.Trigger(
                name="document_change",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n                    IF (TG_OP = 'INSERT') THEN\n                        INSERT INTO nodes_documentevent (public_id, document_type, action, created_at, new_data) VALUES (NEW.public_id, NEW.document_type, 'INSERT', NOW(), NEW.json);\n                    ELSIF (TG_OP = 'UPDATE') THEN\n                        INSERT INTO nodes_documentevent (public_id, document_type, action, created_at, old_data, new_data) VALUES (NEW.public_id, NEW.document_type, 'UPDATE', NOW(), OLD.json, NEW.json);\n                    ELSIF (TG_OP = 'DELETE') THEN\n                        INSERT INTO nodes_documentevent (public_id, document_type, action, created_at, old_data) VALUES (OLD.public_id, OLD.document_type, 'DELETE', NOW(), OLD.json);\n                    END IF;\n                    RETURN NEW;\n                    ",
                    hash="a1c2581becfdddfd0605d0443c4f1eaf9c7394ff",
                    operation="INSERT OR UPDATE OR DELETE",
                    pgid="pgtrigger_document_change_b3491",
                    table="nodes_document",
                    when="AFTER",
                ),
            ),
        ),
    ]
