# Generated by Django 4.2.7 on 2024-03-13 16:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0011_remove_document_document_change_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="node",
            name="public_id",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
