# Generated by Django 4.2.7 on 2024-03-13 16:55

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0012_alter_node_public_id"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="document",
            name="unique_public_id_and_type",
        ),
        migrations.AlterField(
            model_name="node",
            name="public_id",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.UniqueConstraint(
                fields=("public_id", "document_type"),
                name="nodes_document_unique_public_id_and_type",
            ),
        ),
    ]
