# Generated by Django 4.2.7 on 2024-03-20 18:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0013_remove_document_unique_public_id_and_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("EDITOR", "Editor"),
                            ("SPACE", "Space"),
                            ("GRAPH", "Graph"),
                        ],
                        max_length=255,
                    ),
                ),
                ("json_hash", models.CharField(max_length=255)),
                ("data", models.BinaryField()),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="nodes.document",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["public_id"], name="nodes_docum_public__e8eda7_idx"
                    )
                ],
            },
        ),
    ]
