# Generated by Django 4.2.7 on 2024-04-02 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0014_documentversion"),
    ]

    operations = [
        migrations.AddField(
            model_name="space",
            name="default_node",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nodes.node",
            ),
        ),
    ]
