# Generated by Django 4.2.7 on 2024-04-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0015_space_default_node"),
    ]

    operations = [
        migrations.AlterField(
            model_name="space",
            name="deleted_nodes",
            field=models.ManyToManyField(
                blank=True, related_name="spaces_deleted", to="nodes.node"
            ),
        ),
    ]
