# Generated by Django 4.2.7 on 2024-04-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0018_remove_duplicate_document_versions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="node",
            name="title",
            field=models.TextField(default=None, null=True),
        ),
    ]
