# Generated by Django 4.2.7 on 2024-04-23 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0017_node_is_public_node_is_public_writable_and_more"),
        ("nodes", "0018_remove_duplicate_document_versions"),
    ]

    operations = []
