# Generated by Django 4.2.7 on 2024-04-24 10:20

from django.db import migrations, models
import django.db.models.deletion


def backfill_documents(apps, schema_editor):
    Document = apps.get_model("nodes", "Document")
    Node = apps.get_model("nodes", "Node")
    Space = apps.get_model("nodes", "Space")

    for node in Node.objects.only("id", "public_id", "editor_document_id", "graph_document_id"):
        try:
            editor_document = Document.objects.only("id").get(
                public_id=node.public_id, document_type="EDITOR"
            )
        except Document.DoesNotExist:
            editor_document = None

        try:
            graph_document = Document.objects.only("id").get(
                public_id=node.public_id, document_type="GRAPH"
            )
        except Document.DoesNotExist:
            graph_document = None

        node.editor_document_id = editor_document.id if editor_document else None
        node.graph_document_id = graph_document.id if graph_document else None

        node.save(update_fields=["editor_document_id", "graph_document_id"])

    for space in Space.objects.only("id", "public_id", "document_id"):
        try:
            document = Document.objects.only("id").get(
                public_id=space.public_id, document_type="SPACE"
            )
        except Document.DoesNotExist:
            document = None

        space.document_id = document.id if document else None
        space.save(update_fields=["document_id"])


class Migration(migrations.Migration):
    dependencies = [
        ("nodes", "0019_merge_20240423_0858"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="editor_document",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="node_editor",
                to="nodes.document",
            ),
        ),
        migrations.AddField(
            model_name="node",
            name="graph_document",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="node_graph",
                to="nodes.document",
            ),
        ),
        migrations.AddField(
            model_name="space",
            name="document",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="space",
                to="nodes.document",
            ),
        ),
        migrations.RunPython(backfill_documents, migrations.RunPython.noop),
    ]
