# Generated by Django 5.0.4 on 2024-05-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0021_alter_node_is_public_alter_node_is_public_writable_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="node",
            name="title",
            field=models.TextField(default=None, null=True),
        ),
    ]
