# Generated by Django 5.0.4 on 2024-05-08 09:53

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0022_alter_node_title"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="node",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.search.SearchVector(
                    "title", "text", config="english"
                ),
                name="search_vector_idx",
            ),
        ),
    ]
