# Generated by Django 5.1.3 on 2024-11-12 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0026_alter_space_default_node_alter_space_nodes"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="space",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="nodes.space",
            ),
        ),
        migrations.AlterField(
            model_name="space",
            name="default_node",
            field=models.ForeignKey(
                blank=True,
                help_text="The node that gets displayed when a space is opened.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="nodes.node",
            ),
        ),
    ]
