# Generated by Django 5.1.3 on 2024-11-12 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0028_move_spaces_to_space"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="node",
            name="is_public",
        ),
        migrations.RemoveField(
            model_name="node",
            name="is_public_writable",
        ),
        migrations.RemoveField(
            model_name="space",
            name="deleted_nodes",
        ),
        migrations.RemoveField(
            model_name="space",
            name="nodes",
        ),
        migrations.AlterField(
            model_name="node",
            name="space",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nodes",
                to="nodes.space",
            ),
        ),
    ]
