# Generated by Django 5.1.3 on 2024-11-25 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0029_remove_node_is_public_remove_node_is_public_writable_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="space",
            name="title_slug",
        ),
    ]
