# Generated by Django 5.1.3 on 2024-11-25 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0030_remove_space_title_slug"),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="space",
            name="profile",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="space",
                to="profiles.profile",
            ),
        ),
    ]
