# Generated by Django 5.1.3 on 2024-11-25 19:29

from django.db import migrations
import profiles.utils


def fill_profiles(apps, schema_editor):
    Space = apps.get_model("nodes", "Space")
    Profile = apps.get_model("profiles", "Profile")

    for space in Space.objects.filter(profile__isnull=True):
        profile_slug_base = space.title
        profile_slug = profile_slug_base

        while Profile.objects.filter(profile_slug=profile_slug).exists():
            profile_slug = f"{profile_slug_base}-{profiles.utils.random_string(4)}"

        space.profile = Profile.objects.create(profile_slug=profile_slug)
        space.save(update_fields=["profile"])


class Migration(migrations.Migration):
    dependencies = [
        ("nodes", "0031_space_profile"),
    ]

    operations = [migrations.RunPython(fill_profiles, migrations.RunPython.noop)]
