# Generated by Django 5.1.3 on 2024-12-11 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0034_remove_space_profile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="authors",
            field=models.ManyToManyField(
                blank=True, related_name="nodes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="node",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="node",
            name="description",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="node",
            name="description_token_count",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="node",
            name="node_type",
            field=models.CharField(
                choices=[("METHOD", "Method"), ("DEFAULT", "Default")],
                default="DEFAULT",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("EDITOR", "Editor"),
                    ("SPACE", "Space"),
                    ("GRAPH", "Graph"),
                    ("METHOD_GRAPH", "Method Graph"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="documentevent",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("EDITOR", "Editor"),
                    ("SPACE", "Space"),
                    ("GRAPH", "Graph"),
                    ("METHOD_GRAPH", "Method Graph"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="documentversion",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("EDITOR", "Editor"),
                    ("SPACE", "Space"),
                    ("GRAPH", "Graph"),
                    ("METHOD_GRAPH", "Method Graph"),
                ],
                max_length=255,
            ),
        ),
    ]
