# Generated by Django 5.1.4 on 2024-12-30 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0035_node_authors_node_creator_node_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MethodNode",
            fields=[
                (
                    "node_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="nodes.node",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, verbose_name="Public read access"
                    ),
                ),
                (
                    "is_public_writable",
                    models.BooleanField(
                        default=False,
                        verbose_name="Public write access, if public read access is enabled",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("nodes.node", models.Model),
        ),
    ]
