# Generated by Django 5.1.4 on 2025-01-07 18:13

import django.core.validators
import nodes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0036_methodnode"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="image_original",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=nodes.models.unique_node_image_filename,
                validators=[django.core.validators.validate_image_file_extension],
            ),
        ),
    ]
