# Generated by Django 5.1.4 on 2025-01-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0037_node_image_original"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("EDITOR", "Editor"),
                    ("SPACE", "Space"),
                    ("GRAPH", "Graph"),
                    ("METHOD", "Method Graph"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="documentevent",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("EDITOR", "Editor"),
                    ("SPACE", "Space"),
                    ("GRAPH", "Graph"),
                    ("METHOD", "Method Graph"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="documentversion",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("EDITOR", "Editor"),
                    ("SPACE", "Space"),
                    ("GRAPH", "Graph"),
                    ("METHOD", "Method Graph"),
                ],
                max_length=255,
            ),
        ),
    ]
