# Generated by Django 5.1.4 on 2025-01-07 20:40

import django.contrib.postgres.search
import django.core.validators
import django.db.models.deletion
import nodes.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0038_alter_document_document_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="node",
            name="authors",
            field=models.ManyToManyField(
                blank=True,
                related_name="author_%(class)ss",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="node",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="creator_%(class)ss",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="node",
            name="editor_document",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_editor",
                to="nodes.document",
            ),
        ),
        migrations.AlterField(
            model_name="node",
            name="graph_document",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_graph",
                to="nodes.document",
            ),
        ),
        migrations.AlterField(
            model_name="node",
            name="space",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="nodes.space",
            ),
        ),
        migrations.CreateModel(
            name="MethodNodeVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_removed", models.BooleanField(default=False)),
                ("title", models.TextField(default=None, null=True)),
                ("title_token_count", models.PositiveIntegerField(null=True)),
                ("description", models.TextField(default=None, null=True)),
                ("description_token_count", models.PositiveIntegerField(null=True)),
                ("content", models.JSONField(null=True)),
                ("text", models.TextField(default=None, null=True)),
                ("text_token_count", models.PositiveIntegerField(null=True)),
                (
                    "node_type",
                    models.CharField(
                        choices=[("METHOD", "Method"), ("DEFAULT", "Default")],
                        default="DEFAULT",
                        max_length=255,
                    ),
                ),
                (
                    "image_original",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=nodes.models.unique_node_image_filename,
                        validators=[
                            django.core.validators.validate_image_file_extension
                        ],
                    ),
                ),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        editable=False, null=True
                    ),
                ),
                ("version", models.PositiveSmallIntegerField()),
                (
                    "authors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="author_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="creator_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="method_versions",
                        to="nodes.documentversion",
                    ),
                ),
                (
                    "editor_document",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_editor",
                        to="nodes.document",
                    ),
                ),
                (
                    "graph_document",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_graph",
                        to="nodes.document",
                    ),
                ),
                (
                    "method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="nodes.methodnode",
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="nodes.space",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="methodnode",
            name="forked_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nodes.methodnodeversion",
            ),
        ),
        migrations.AddConstraint(
            model_name="methodnodeversion",
            constraint=models.UniqueConstraint(
                fields=("method", "version"), name="unique_method_version"
            ),
        ),
    ]
