# Generated by Django 5.1.5 on 2025-01-28 10:40

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buddies", "0002_alter_buddy_model_alter_buddy_system_message"),
        ("nodes", "0041_remove_methodnodeversion_editor_document_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="methodnode",
            managers=[
                ("available_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="methodnode",
            name="buddy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="buddies.buddy",
            ),
        ),
        migrations.AddField(
            model_name="methodnodeversion",
            name="buddy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="buddies.buddy",
            ),
        ),
    ]
