# Generated by Django 5.1.9 on 2025-05-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0042_alter_methodnode_managers_methodnode_buddy_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="methodnoderun",
            name="nodes_metho_public__89eb37_idx",
        ),
        migrations.AddField(
            model_name="methodnoderun",
            name="is_public",
            field=models.BooleanField(default=False, verbose_name="Public read access"),
        ),
        migrations.AddField(
            model_name="methodnoderun",
            name="is_public_writable",
            field=models.BooleanField(
                default=False,
                verbose_name="Public write access, if public read access is enabled",
            ),
        ),
    ]
