# Generated by Django 5.2.3 on 2025-06-25 19:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0042_alter_methodnode_managers_methodnode_buddy_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="node",
            index=models.Index(fields=["is_removed"], name="node_is_removed_idx"),
        ),
    ]
