#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "coordnet-hocuspocus"
primary_region = "ams"
kill_timeout = 30
swap_size_mb = 1024

[build]
  dockerfile = "compose/crdt/Dockerfile"

[build.args]
  BUILD_ENVIRONMENT= "production"

[env]
  SENTRY_ENVIRONMENT="production"
#  POSTGRES_USER="coordnet_hocuspocus"
#  POSTGRES_PORT=5432
#  POSTGRES_DB="coordnet"

[http_service]
  internal_port = 8010
  # force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 1
  tls_options = {"alpn"= ["h2", "http/1.1"],  "default_self_signed"= true}
  processes = ["crdt"]

[http_service.concurrency]
  hard_limit = 2000
  soft_limit = 1750

[processes]
  crdt = "pnpm start:server"
  worker = "pnpm start:worker"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 768

[[restart]]
  policy = "always"
