# Generated by Django 5.0.4 on 2024-05-06 10:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("permissions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="objectmembershiprole",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("member", "Member"),
                    ("viewer", "Viewer"),
                ],
                default="member",
                max_length=10,
                unique=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="objectmembership",
            constraint=models.UniqueConstraint(
                fields=("user", "content_type", "object_id"), name="unique_membership"
            ),
        ),
    ]
