# Generated by Django 5.0.4 on 2024-05-06 12:45

from django.db import migrations


def delete_soft_deleted_permissions(apps, schema_editor):
    ObjectMembership = apps.get_model("permissions", "ObjectMembership")
    ObjectMembership.objects.filter(is_removed=True).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("permissions", "0002_alter_objectmembershiprole_role_and_more"),
    ]

    operations = [
        migrations.RunPython(
            delete_soft_deleted_permissions, reverse_code=migrations.RunPython.noop
        )
    ]
