# Generated by Django 5.1.9 on 2025-05-29 19:27

import uploads.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_removed", models.BooleanField(default=False)),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, verbose_name="Public read access"
                    ),
                ),
                (
                    "is_public_writable",
                    models.BooleanField(
                        default=False,
                        verbose_name="Public write access, if public read access is enabled",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to=uploads.models.user_upload_path)),
                ("content_type", models.CharField(blank=True, max_length=255)),
                ("size", models.PositiveIntegerField(default=0)),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["public_id"], name="uploads_use_public__3f80fe_idx"
                    )
                ],
            },
        ),
    ]
