# Generated by Django 5.1.8 on 2025-05-04 15:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PaperQACollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_removed", models.BooleanField(default=False)),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, verbose_name="Public read access"
                    ),
                ),
                (
                    "is_public_writable",
                    models.BooleanField(
                        default=False,
                        verbose_name="Public write access, if public read access is enabled",
                    ),
                ),
                ("name", models.SlugField(max_length=255, unique=True)),
                ("files", models.BinaryField(blank=True, null=True)),
                ("index", models.BinaryField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
