# Generated by Django 5.1.9 on 2025-05-29 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0001_initial"),
        ("uploads", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paperqacollection",
            name="files",
        ),
        migrations.RemoveField(
            model_name="paperqacollection",
            name="index",
        ),
        migrations.AddField(
            model_name="paperqacollection",
            name="state",
            field=models.CharField(
                choices=[
                    ("ready", "Ready"),
                    ("waiting", "Waiting"),
                    ("processing", "Processing"),
                    ("error", "Error"),
                ],
                default="ready",
                help_text="Current state of the collection",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="paperqacollection",
            name="uploads",
            field=models.ManyToManyField(
                blank=True, related_name="collections", to="uploads.userupload"
            ),
        ),
        migrations.AddIndex(
            model_name="paperqacollection",
            index=models.Index(
                fields=["public_id"], name="tools_paper_public__a58bb8_idx"
            ),
        ),
    ]
