#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python /app/backend/manage.py collectstatic --noinput

exec /usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/app/backend --workers 3 --timeout 120
