#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python /app/backend/manage.py collectstatic --noinput

exec gunicorn --access-logfile="-" --workers 3 --bind '[::]:5000' --chdir=/app/backend -k uvicorn.workers.UvicornWorker config.asgi:application
