apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data-pvc
  namespace: coordnet
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: coordnet
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30002
  selector:
    app: minio

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: coordnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: bitnami/minio:2025.4.22
          ports:
            - containerPort: 9000
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: coordnet-secrets
                  key: MINIO_ROOT_USER
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: coordnet-secrets
                  key: MINIO_ROOT_PASSWORD
            - name: MINIO_DEFAULT_BUCKETS
              valueFrom:
                configMapKeyRef:
                  name: coordnet-config
                  key: MINIO_DEFAULT_BUCKETS
          volumeMounts:
            - name: minio-data
              mountPath: /bitnami/minio/data
      volumes:
        - name: minio-data
          persistentVolumeClaim:
            claimName: minio-data-pvc
