apiVersion: v1
kind: Secret
metadata:
  name: coordnet-secrets
  namespace: coordnet
type: Opaque
data:
  DATABASE_URL: <BASE64_ENCODED_DATABASE_URL>
  DJANGO_SECRET_KEY: <BASE64_ENCODED_DJANGO_SECRET_KEY>
  DJANGO_ADMIN_URL: <BASE64_ENCODED_DJANGO_ADMIN_URL>
  WEBSOCKET_API_KEY: <BASE64_ENCODED_WEBSOCKET_API_KEY>
  SEMANTIC_API_KEY: <BASE64_ENCODED_SEMANTIC_API_KEY>
  MAILGUN_API_KEY: <BASE64_ENCODED_MAILGUN_API_KEY>

  # If you are using Open AI then set this
  OPENAI_API_KEY: <BASE64_ENCODED_OPENAI_API_KEY>

  # If you are using Azure OpenAI then uncomment and set this
  # AZURE_OPENAI_API_KEY: <BASE64_ENCODED_AZURE_OPENAI_API_KEY>
