apiVersion: v1
kind: Secret
metadata:
  name: coordnet-secrets
  namespace: coordnet
type: Opaque
data:
  DATABASE_URL: <BASE64_ENCODED_DATABASE_URL>
  DJANGO_SECRET_KEY: <BASE64_ENCODED_DJANGO_SECRET_KEY>
  DJANGO_ADMIN_URL: <BASE64_ENCODED_DJANGO_ADMIN_URL>
  SEMANTIC_API_KEY: <BASE64_ENCODED_SEMANTIC_API_KEY>
  MAILGUN_API_KEY: <BASE64_ENCODED_MAILGUN_API_KEY>

  # This is the private part of a RSA key
  JWT_SIGNING_KEY: <BASE64_ENCODED_JWT_SIGNING_KEY>

  # This is the public part of a RSA key
  JWT_VERIFYING_KEY: <BASE64_ENCODED_JWT_VERIFYING_KEY>

  # If you are using Open AI then set this
  OPENAI_API_KEY: <BASE64_ENCODED_OPENAI_API_KEY>

  # If you are using Azure OpenAI then uncomment and set this
  # AZURE_OPENAI_API_KEY: <BASE64_ENCODED_AZURE_OPENAI_API_KEY>

  # For Minio (if using)
  MINIO_ROOT_USER: <BASE64_ENCODED_MINIO_ROOT_USER>
  MINIO_ROOT_PASSWORD: <BASE64_ENCODED_MINIO_ROOT_PASSWORD>

  # For S3 client authentication (the same as Minio if using otherwise your S3 creds)
  AWS_ACCESS_KEY_ID: <BASE64_ENCODED_AWS_ACCESS_KEY_ID>
  AWS_SECRET_ACCESS_KEY: <BASE64_ENCODED_AWS_SECRET_ACCESS_KEY>

  # For Azure Storage (if using, only one of the following is needed)
  # AZURE_ACCOUNT_KEY: <BASE64_ENCODED_AZURE_ACCOUNT_KEY>
  # AZURE_CONNECTION_STRING: <BASE64_ENCODED_AZURE_CONNECTION_STRING>
