# Generated by Django 5.1.8 on 2025-05-01 12:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LLModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("identifier", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "is_available",
                    models.BooleanField(
                        default=True, verbose_name="Available for new items"
                    ),
                ),
                (
                    "disabled",
                    models.BooleanField(
                        default=False, verbose_name="Will not be executed"
                    ),
                ),
                (
                    "input_token_limit",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "output_token_limit",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "replacement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="llms.llmodel",
                        verbose_name="Replacement for unavailable models.",
                    ),
                ),
            ],
            options={
                "verbose_name": "LLM",
                "verbose_name_plural": "LLMs",
                "ordering": ["name"],
            },
        ),
    ]
