# Generated by Django 5.1.10 on 2025-06-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmodel",
            name="api_base",
            field=models.CharField(
                blank=True,
                help_text="Custom API base URL for this model (if different from default)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="llmodel",
            name="provider",
            field=models.CharField(
                choices=[
                    ("openai", "OpenAI"),
                    ("azure", "Azure OpenAI"),
                    ("anthropic", "Anthropic"),
                    ("google_ai", "Google AI Studio"),
                    ("cohere", "Cohere"),
                    ("mistral", "Mistral AI"),
                    ("other", "Other"),
                ],
                default="openai",
                help_text="The provider of this LLM",
                max_length=50,
            ),
        ),
    ]
