# Generated by Django 5.1.3 on 2024-11-26 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0033_alter_space_profile"),
        ("profiles", "0003_profilecard_is_public"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="is_public",
        ),
        migrations.AddField(
            model_name="profile",
            name="draft",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="new_space",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="nodes.space",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="new_user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="profilecard",
            name="draft",
            field=models.BooleanField(default=True),
        ),
    ]
