# Generated by Django 5.1.3 on 2024-11-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0007_profilecard_space_alter_profile_space_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profilecard",
            name="profile",
        ),
        migrations.AddField(
            model_name="profile",
            name="cards",
            field=models.ManyToManyField(
                blank=True, related_name="profiles", to="profiles.profilecard"
            ),
        ),
    ]
