# Generated by Django 5.1.3 on 2024-11-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "profiles",
            "0009_remove_profilecard_author_remove_profilecard_space_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="profilecard",
            name="status_message",
            field=models.TextField(blank=True),
        ),
    ]
