# Generated by Django 5.1.3 on 2024-12-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0010_profilecard_status_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
