# Generated by Django 4.2.7 on 2024-03-13 09:04

from django.db import migrations, models
import uuid


def create_uuid(apps, schema_editor):
    User = apps.get_model("users", "User")
    for user in User.objects.all():
        user.public_id = uuid.uuid4()
        user.save()


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="public_id",
            field=models.UUIDField(blank=True, null=True, verbose_name="Public ID"),
            preserve_default=False,
        ),
        migrations.RunPython(create_uuid, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="user",
            name="public_id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name="Public ID",
            ),
        ),
    ]
