# Generated by Django 5.1.3 on 2024-11-26 15:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_user_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="profile",
        ),
    ]
