# Generated by Django 4.2.7 on 2024-03-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="node",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="project",
            name="deleted_nodes_strings",
        ),
        migrations.RemoveField(
            model_name="project",
            name="is_deleted",
        ),
        migrations.AlterField(
            model_name="project",
            name="deleted_nodes",
            field=models.ManyToManyField(
                related_name="projects_deleted", to="nodes.node"
            ),
        ),
    ]
