# Generated by Django 4.2.7 on 2024-03-12 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0004_alter_document_public_id_alter_node_content_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Project",
            new_name="Space",
        ),
        migrations.RenameIndex(
            model_name="space",
            new_name="nodes_space_public__848cd3_idx",
            old_name="nodes_proje_public__53dff1_idx",
        ),
    ]
