# Generated by Django 4.2.7 on 2024-03-12 17:13

from django.db import migrations
from django_celery_beat.models import PeriodicTask, IntervalSchedule


def create_periodic_task(apps, schema_editor):
    # Create a schedule that runs every 30 seconds
    schedule, _ = IntervalSchedule.objects.get_or_create(
        every=30, period=IntervalSchedule.SECONDS
    )

    # Create a periodic task that uses this schedule
    PeriodicTask.objects.update_or_create(
        interval=schedule,
        name="Check trigger events every 30 seconds",
        defaults={"task": "nodes.tasks.process_document_events"},
    )

    PeriodicTask.objects.filter(task="nodes.tasks.check_trigger_events").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("nodes", "0009_documentevent_document_type"),
    ]

    operations = [
        migrations.RunPython(
            create_periodic_task, reverse_code=migrations.RunPython.noop
        )
    ]
